### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by lovistawiah** [znx-x/llane-ui#3]
I find your idea very lively and I want to be an active **contributor** to your project

**Comment by znx-x** [comment]
Hey @lovistawiah great to hear and all I can say really is welcome onboard! There's still early days, so a lot of stuff that we can do and components we can add to make llane-ui more suitable for production environments. Amongst them:

- Adding more props to all components;
- Enhancing the icons library to include more up to date social icons (like X for example) and more general use icons;
- Adding checkbox, radio button, floating action button, transfer list, and so on

I've taken a lot of the ideas from Material UI, the idea being to improve upon their model to make something that has a set standard but is also flexible enough that every component can be stylised with JS, giving developers a framework but full control over it

Feel free to let me know your thoughts. Being an open source project in such early stages, the roadmap is still very fluid.

**Comment by lovistawiah** [comment]
I will run the project locally, write some ideas and share it with you

**Comment by znx-x** [comment]
Looking forward to it then. Let me know if there's any info you need when you do so, as I still haven't written any docs on it.
